//Jordan Cole
//CO SCI_802_26188FA19V
//Final Programming Assignment
//Program that generates a random number between 1 and 100 and asks the user to guess what the number is.
//If the users guess is too high, program displays "Too high, try again" / too low, displays "Too low, try again".
//Uses a loop that repeats until the user correctly guesses, then displays "Congratulations. You got it".
//Also displays the random number generated by the program, and how many guesses it took the user to guess correctly.

#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

int main()
{
    
    //Creat constants variables for the min/max parameters
	const int Min_Num = 1, Max_Num = 100;
	
	//Create variable for number of iterations (NOI), the random number, and the user number
	int NOI = 1, Rand_Num, User_Num;
	
	//Random number generation
	int seed = time(0);
	srand(seed);
	Rand_Num = 1 + (rand() % (Max_Num));
    
    //Introduction to the program
    cout << "I am thinking of a number between " << Min_Num <<  " and " << Max_Num << "." << endl ;
    cout << "Can you guess what it is? Enter your guess: ";
    
    //User input
    cin >> User_Num;
    
    //use do/while loop to guarantee at least one iteration
    do
    {
        //input validation, if users number does not fall within min/max parameters / counts an interation and receives new input
        if ((User_Num < Min_Num) || (User_Num > Max_Num))
        {
            cout << endl << "The number is between " << Min_Num << " and " << Max_Num << "." << " Please guess again: ";
            NOI++;
            cin >> User_Num;
        }
        
        //input validation, tells user the number is too low / counts an interation and receives new input
        if ((User_Num < Rand_Num) && (User_Num >= Min_Num) && (User_Num <= Max_Num))
        {
            cout << endl << User_Num << " is too low. Try a larger number. ";
            NOI++;
            cin >> User_Num;
        }
        
        //input validation, tells user the number is too high / counts an iteration and receives new input
        if ((User_Num > Rand_Num) && (User_Num >= Min_Num) && (User_Num <= Max_Num))
        {
            cout << endl << User_Num << " is too high. Try a smaller number. ";
            NOI++;
            cin >> User_Num;
        }
    } while (User_Num != Rand_Num);
    
    //Exit the loop once the user number matches the random number, display to user
    cout << endl << "Congratulations! You got it, my number was " << Rand_Num << "." << endl;
    
    //Display the number of guesses (different for 1 guess because "1 guesses" would be grammatically incorrect)
    if (NOI > 1)
        cout << "It took you " << NOI << " guesses." << endl;
    else
        cout << "You got it on the first guess!" << endl;

	return 0;
}
